image: Visual Studio 2017
configuration: Release
platform: x64

branches:
  only:
  - master

environment:
  matrix:
  - platform: amd64
    qt: msvc2017_64

init:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

install:
- cmd: >-
    SET QTDIR=C:\Qt\5.12\msvc2017_64
    
    SET OPENSSL=C:\OpenSSL-v111-Win64
    
    SET PATH=%OPENSSL%\bin;%QTDIR%\bin;%PATH%;

build_script:
- cmd: >-
    qmake mapleseed.pro -spec win32-msvc
    
    C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile

artifacts:
  - path: mapleseed.zip
    name: mapleseed
    
after_build:
  - ps: 7z a C:\projects\mapleseed\mapleseed.zip C:\projects\mapleseed\release\*.exe C:\OpenSSL-v111-Win64\bin\libcrypto-1_1-x64.dll C:\OpenSSL-v111-Win64\bin\libssl-1_1-x64.dll
  