image: Visual Studio 2017
configuration: Release
platform: x64

branches:
  only:
  - master

environment:
  matrix:
  - platform: amd64
    qt: msvc2017_64

init:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

install:
- cmd: >-
    SET QTDIR=C:\Qt\5.12\msvc2017_64
    
    SET OPENSSL=C:\OpenSSL-v111-Win64
    
    SET PATH=%OPENSSL%\bin;%QTDIR%\bin;%PATH%;

build_script:
- cmd: >-
    qmake mapleseed.pro -spec win32-msvc
    
    C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile

artifacts:
  - path: .\*.zip
    name: Mapleseed
    
after_build:
  - ps: 7z a mapleseed_canary_1.1.0-{build}.zip C:\projects\mapleseed\CemuCrypto\release\*.dll C:\projects\mapleseed\CemuDatabase\release\*.dll C:\projects\mapleseed\CemuLibrary\release\*.dll C:\projects\mapleseed\Network\release\*.dll C:\projects\mapleseed\Core\release\*.exe
  